# https://alacritty.org/config-alacritty.html
[general]
import = ["~/.config/alacritty/rose-pine-moon.toml"]

[window]
blur = true
opacity = 1.0
decorations = "None"
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMonoNerdFont" }
size = 15

[env]
TERM = "xterm-256color"
ALACRITTY = "true"

[keyboard]
bindings = [
{ key = "N", mods = "Command", action = "CreateNewWindow"},
]
