# https://alacritty.org/config-alacritty.html
import = ["~/.config/alacritty/rose-pine-moon.toml"]

live_config_reload = true

[window]
blur = true
opacity = 1.0
decorations = "None"
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 17

# TokyoNight Alacritty Colors
# background = '#24283b'
# foreground = '#c0caf5'

# Normal colors
# [colors.normal]
# black = '#1d202f'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#bb9af7'
# cyan = '#7dcfff'
# white = '#a9b1d6'

# Bright colors
# [colors.bright]
# black = '#414868'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#bb9af7'
# cyan = '#7dcfff'
# white = '#c0caf5'

[keyboard]
bindings = [
{ key = "N", mods = "Command", action = "CreateNewWindow"},
]
