-- vim.lsp.config.jdtls = {
-- 	cmd = { vim.fn.expand("~/.local/share/nvim/mason/bin/jdtls") },
-- 	root_dir = vim.fs.dirname(vim.fs.find({ "gradlew", ".git", "mvnw" }, { upward = true })[1]),
-- }
-- vim.lsp.enable({ "jdtls", "gradle_ls" })
