#!/bin/zsh

export PATH=$PATH:/home/ethan/cmake/bin
export PATH=$PATH:/home/ethan/.cargo/bin

export PATH=$PATH:/home/ethan/go/bin
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:/home/linuxbrew/.linuxbrew/bin

export EDITOR='nvim'
export COLOR='magenta'

alias term="alacritty&; disown && exit" 

echo $ALACRITTY
if [[ $ALACRITTY != true ]] && [[ -z $SSH_CONNECTION ]] then
	# alacritty&; disown && exit	
fi
