#!/bin/zsh

alias lucy='ssh root@lucy'
alias du='gdu'

# Wrap nvm in setup function so initial shell load doesn't take forever
nvm() {
    unset -f nvm
    if [[ -z $NVM_DIR ]]; then
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
    fi
    nvm $@
}
unset NVM_DIR

colorscript() {
    ~/repos/external/shell-color-scripts/colorscript.sh $@
}

fix_vips() {
    vipsVersion=$(ls /opt/homebrew/Cellar/vips/)
    echo "Fixing vips version $vipsVersion"
    ln -s /opt/homebrew/Cellar/vips/$vipsVersion/lib/pkgconfig/vips.pc /opt/homebrew/lib/pkgconfig/vips.pc
}

alias start-docker='open -a Docker'

export EDITOR='nvim'
export COLOR='magenta'

add_to_path() {
    if [[ $2 == true ]]; then
        if [[ $SHELLY_DEBUG == true ]]; then
            echo "Overriding PATH entry $1 to be at top"
        fi
        export PATH=$(echo $PATH | sed -r -e "s|${1}:?||g")
    fi
    if [[ ":$PATH:" != *":$1:"* ]]; then
        if [[ $SHELLY_DEBUG == true ]]; then
            echo "Adding $1 to PATH"
        fi
        export PATH=$1:$PATH
    fi
}

add_to_path "$HOME/.cargo/bin"
add_to_path "/Library/Frameworks/Python.framework/Versions/3.10/bin"
add_to_path "/opt/homebrew/bin"
add_to_path "/Users/ethan/go/bin"
add_to_path "/Users/ethan/Library/Python/3.10/bin"
add_to_path "/opt/homebrew/bin" true
add_to_path "/opt/homebrew/sbin" true
add_to_path "/opt/homebrew/opt/python@3.12/libexec/bin" true

# Make tmux play nice with emacs keybindings
bindkey -e

export CPATH="/opt/homebrew/include/"
