#!/bin/zsh

alias lucy='ssh root@lucy'
alias du='gdu'

nvm() {
    unset -f nvm
    if [[ -z $NVM_DIR ]]; then
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
    fi
    nvm $@
}
unset NVM_DIR

colorscript() {
    ~/repos/external/shell-color-scripts/colorscript.sh $@
}

fix_vips() {
    vipsVersion=$(ls /opt/homebrew/Cellar/vips/)
    echo "Fixing vips version $vipsVersion"
    ln -s /opt/homebrew/Cellar/vips/$vipsVersion/lib/pkgconfig/vips.pc /opt/homebrew/lib/pkgconfig/vips.pc
}

alias start-docker='open -a Docker'

export EDITOR='nvim'
export COLOR='magenta'

add_to_path() {
    if [[ ":$PATH:" != *":$1:"* ]]; then
        export PATH=$PATH:$1
    fi
}

add_to_path "$HOME/.cargo/bin"
add_to_path "/Library/Frameworks/Python.framework/Versions/3.10/bin"
add_to_path "/opt/homebrew/bin"
add_to_path "/Users/ethan/go/bin"
add_to_path "/Users/ethan/Library/Python/3.10/bin"

# Make tmux play nice with emacs keybindings
bindkey -e

export CPATH="/opt/homebrew/include/"

if ! pgrep ollama-copilot >/dev/null; then
    ollama-copilot >/dev/null 2>&1 &
fi

#PATH=$PATH:$(/usr/local/go/bin/go env GOPATH)/bin
#PATH="$PATH:/usr/local/mysql/bin"
#PATH="$PATH:/Library/Frameworks/Python.framework/Versions/3.10/bin"
#PATH="$PATH:/opt/homebrew/Cellar/mongosh/1.8.0/bin"
