#!/bin/bash

### Alias ###
alias dps="sudo docker ps --format \"table {{.ID}} \t{{.Status}} \t{{.Names}}\""
alias ebrc="cd $SHELLY && e ."
alias v='ls -l'
alias va='ls -la'
alias n='ping 1.1.1.1'
alias whoamip='curl -s ifconfig.me'
alias ip='ifconfig | grep 10.10.1'
alias pathls='echo $PATH | tr ":" "\n"'
alias tab='wezterm cli set-tab-title'

alias sbp="source ~/.${SHELL_NAME}rc"
alias sync="$SHELLY/shell/common/auto-loader.bash"

export EDITOR="e"

### Funcs ###

function run_cmd() {
  if [[ $2 =~ ^([^@]+@)?([^:]+):(.*)$ ]]; then
    ssh $match[1]$match[2] $1 $match[3]
  else
    $(which $1) $2 $3
  fi
}

dock() {
	docker exec -it "$1" "${2:-bash}"
}

cat() {
    run_cmd /bin/cat "${@: -1}"
}

ls() {
    # $1 is the options for lsd, use $2
    if which eza >/dev/null 2>&1; then
      run_cmd eza "$1" "${@: -1}"
    else
      run_cmd /usr/bin/ls "$1" "${@: -1}"
    fi
}

e () {
    if [[ -z "$@" ]]; then
        if [[ ! -d $HOME/.config/nvim/session ]]; then
            mkdir -p $HOME/.config/nvim/session
        fi

        session_path="${PWD//\//-}"
        session_path="$HOME/.config/nvim/session/${session_path:1}.session.vim"
	if [[ -f $session_path ]]; then
	    nvim -S "$session_path" -c 'lua vim.g.savesession = true'
	else
	    nvim -c 'lua vim.g.savesession = true'
	fi
    else
    	nvim "$@"
    fi
}

man() {
	nvim -c ":Man $1 | :only"
}

dbg() {
    if [[ $SHELLY_DEBUG == true ]]; then
        export SHELLY_DEBUG=false
        echo "SHELLY_DEBUG DISABLED"
    else
        export SHELLY_DEBUG=true
        echo "SHELLY_DEBUG ENABLED"
    fi
}

search() {
  DIR=""
  if [[ "$2" != "" ]]; then
	  DIR="$2"
  else
	  DIR=.
  fi
  find "$DIR" -name "*$1*" 2>&1 | grep -v "find: "
}

searchall() {
    find / -name "$1" 2>&1 | grep -v "find: "
}

known-host-rm() {
  cat ~/.ssh/known_hosts | grep -v $1 > ~/.ssh/known_hosts
}

printProcess() {
	printf "\n------ Processes Matching \"$1\" ------\n$(ps aux | grep "$1" | grep -v grep | awk '{print $2, $11}')\n\n"
}

getme() {
  if [[ "$1" == "" ]]
  then
    echo "No filename specified"
    return
  fi

  files=$(find . -type f -name "*$1*")
  files=("${(@s:\n:)files}")
  echo "Reading $files[1]"
  cat $files[1]
}

mcsay() {
  text="\"$@\""

  command="/Users/ethan/repos/mcrcon/mcrcon -H lucy.arcticnet -p minecraft1234 "
  command+=\'
  command+="tellraw @a "
  command+=$text
  command+=\'
  eval "$command"
  # ~/repos/mcrcon/mcrcon -H lucy.arcticnet -p minecraft1234 $(echo $command)
}

port() {
    echo "Finding processes listening on port $1..."
    lsof -n -i4TCP:$1 | grep LISTEN
}

kill-ollama() {
	pkill ollama-copilot
}

add_to_path() {
	if [[ $2 == true ]]; then
		if [[ $SHELLY_DEBUG == true ]]; then
			echo "Overriding PATH entry $1 to be at top"
		fi
		export PATH=$(echo $PATH | sed -r -e "s|${1}:?||g")
	fi
	if [[ ":$PATH:" != *":$1:"* ]]; then
		if [[ $SHELLY_DEBUG == true ]]; then
			echo "Adding $1 to PATH"
		fi
		export PATH=$1:$PATH
	fi
}

# Wrap nvm in setup function so initial shell load doesn't take forever
nvm() {
    unset -f nvm
    if [[ -z $NVM_DIR ]]; then
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
		add_to_path $(nvm which default) true
    fi
    nvm $@
}
unset NVM_DIR

if which ollama-copilot >/dev/null; then
    if ! pgrep ollama-copilot >/dev/null; then
        echo "Launching ollama-copilot"
		export OLLAMA_HOST="lucy.arcticnet:11439"
		mkdir -p ~/.config/logs
        ollama-copilot >~/.config/logs/ollama.log 2>&1 &

        # Detatch from new process
        disown
    fi
fi

# export LDFLAGS="-L/opt/homebrew/lib"
# export CPPFLAGS="-I/opt/homebrew/include"

# Danger??
# ulimit -n 4096

