#!/bin/zsh

export PATH=$PATH:/home/ethan/cmake/bin
export PATH=$PATH:/home/ethan/.cargo/bin

export PATH=$PATH:/home/ethan/go/bin
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:/home/linuxbrew/.linuxbrew/bin

export EDITOR='nvim'
export COLOR='magenta'

bindkey -e

if [[ $ALACRITTY != true ]] then
	alacritty&; disown && exit	
fi
