#!/bin/bash

# This is the entry point for reading the bash configuration.
# It sources all files in ~/shelly/shell/bash/source/

count=0
for f in $SHELLY/shell/bash/source/*; do
    ((count++))
    if [[ $SHELLY_DEBUG == "true" ]]; then
        echo "SOURCING $f"
    fi

    source $f
done
