#!/bin/zsh

# This is the entry point for reading the zsh configuration.
# It sources all files in ~/shelly/zsh_conf/ and ~/shelly/zsh_machine_$HOST

count=0
for f in "$SHELLY"/shell/zsh/source/*; do
    ((count++))
    if [[ $SHELLY_DEBUG == "true" ]]; then
        echo "SOURCING $f"
    fi

    source $f
done

