#!/bin/zsh

autoload -Uz vcs_info
precmd() { vcs_info }

zstyle ':vcs_info:git:*' formats '%F{red}(%b)%f '

setopt PROMPT_SUBST
PROMPT='[%F{$COLOR}%t %m%f] %11F%~%f ${vcs_info_msg_0_}%f$ '

if [[ $SHELLY_DEBUG == "true" ]]; then
    echo "Set Prompt $PROMPT"
fi

export HOMEBREW_NO_ENV_HINTS=true
add_to_path "/opt/homebrew/opt/ruby/bin"

todo() {
    if [[ -n "$1" ]]; then
        if [[ "$1" == "add" ]]; then
            echo "- [ ] ${@:2}" >>~/docs/todo.md
            echo "Added todo: ${@:2}"
        elif [[ "$1" == "edit" || "$1" == "e" ]]; then
            nvim ~/docs/todo.md
            return
        elif [[ "$1" == "rm" ]]; then
            args="${@:2}"
            sed -i '' "/${args}/d" ~/docs/todo.md
            echo "Removed todo: ${@:2}"
        else
            echo "Unknown argument: $1"
            echo "Usage: todo [add] <todo item>"
            return
        fi
    fi

    glow ~/docs/todo.md
}

# OPENROUTER_API_KEY=$(op read "op://Private/OpenRouter/API KEY")
# export OPENROUTER_API_KEY
# export ANTHROPIC_BASE_URL="https://openrouter.ai/api"
# export ANTHROPIC_AUTH_TOKEN="$OPENROUTER_API_KEY"
# export ANTHROPIC_API_KEY="" # Important: Must be explicitly empty
# export ANTHROPIC_DEFAULT_OPUS_MODEL="qwen/qwen3.6-plus:free"
# export ANTHROPIC_DEFAULT_SONNET_MODEL="qwen/qwen3.6-plus:free"
# export ANTHROPIC_DEFAULT_HAIKU_MODEL="qwen/qwen3.6-plus:free"
# export CLAUDE_CODE_SUBAGENT_MODEL="qwen/qwen3.6-plus:free"
