#!/bin/bash

export USE_CCACHE=1

export PNPM_HOME="/Users/erousseau/Library/pnpm"

add_to_path "$HOME/.cargo/bin"
# add_to_path "/Library/Frameworks/Python.framework/Versions/3.10/bin"
add_to_path "/opt/homebrew/bin"
add_to_path "/Users/erousseau/go/bin"
# add_to_path "/Users/ethan/Library/Python/3.10/bin"
add_to_path "/opt/homebrew/bin" true
add_to_path "/opt/homebrew/sbin" true
# add_to_path "/opt/homebrew/opt/python@3.12/libexec/bin" true
add_to_path "/Users/erousseau/.local/share/nvim/mason/bin"
add_to_path "$PNPM_HOME" true
add_to_path "/Users/erousseau/.rd/bin"
add_to_path "/Users/erousseau/.local/bin"
add_to_path "/Users/erousseau/.pyenv/versions/3.12.3/bin"
add_to_path "/opt/homebrew/opt/ruby/bin"

source "$SHELLY/shell/$SHELL_NAME/machines/EROUSSEAU0ML"
