#!/bin/bash

add_to_path "$HOME/.cargo/bin"
add_to_path "/Library/Frameworks/Python.framework/Versions/3.10/bin"
add_to_path "/opt/homebrew/bin"
add_to_path "/Users/ethan/go/bin"
add_to_path "/Users/ethan/Library/Python/3.10/bin"
add_to_path "/opt/homebrew/bin" true
add_to_path "/opt/homebrew/sbin" true
add_to_path "/opt/homebrew/opt/python@3.12/libexec/bin" true
add_to_path "/Users/erousseau/.local/share/nvim/mason/bin"

