name: Test Setup

on:
  workflow_dispatch

jobs:
  setup-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          source ./zsh/zsh_main
          ./zsh/setup.zsh
        shell: zsh {0}
